name: Update Heatmap

on:
  schedule:
    - cron: '0 * * * *' # every hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Restore Firebase key
        run: |
          echo "${{ secrets.FIREBASE_KEY_JSON }}" | base64 --decode > firebase-key.json
          echo "firebase-key.json created"

      - name: Set credentials env
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-key.json" >> $GITHUB_ENV

      - name: Generate heatmap
        run: go run main.go

      - name: Copy heatmap to web/public directory
        run: |
          mkdir -p web/public
          cp public/heatmap.json web/public/heatmap.json
          echo "Copied heatmap.json to web/public directory"

      - name: Commit and push heatmap and timestamp
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase origin main
          mkdir -p web/public
          cp public/heatmap.json web/public/heatmap.json
          git add public/heatmap.json public/last_timestamp.txt web/public/heatmap.json
          git commit -m "Update heatmap and timestamp [CI skip]" || echo "No changes to commit"
          git push origin main

      - name: Trigger Deploy Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy


